[package]
name = "adapter_sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
ports            = { path = "../../ports" }
domain_flashcard = { path = "../../domain/flashcard" }
domain_tagging   = { path = "../../domain/tagging" }
domain_auth      = { path = "../../domain/auth" }
rusqlite         = { version = "0.37.0", features = ["bundled", "functions"] }
regex            = "1"
serde_json       = "1"
uuid             = { version = "1", features = ["v4"] }
